DELIMITER $$
CREATE PROCEDURE agent()
BEGIN
DECLARE done INT DEFAULT FALSE;
DECLARE CUST_NAME varchar(40);
DECLARE CUST_CITY varchar(35);
DECLARE CUST_COUNTRY varchar(20);
DECLARE GRADE decimal(10,0);


DECLARE cursor_cus CURSOR FOR SELECT
CUST_NAME, CUST_CITY, CUST_COUNTRY, GRADE FROM customer WHERE AGENT_CODE REGEXP '^[A00]';

DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

OPEN cursor_cus;

read_loop: LOOP

FETCH cursor_cus INTO 
CUST_NAME,
CUST_CITY,
CUST_COUNTRY,
GRADE;
IF done THEN
      LEAVE read_loop;
    END IF;
SELECT CUST_NAME, CUST_CITY, CUST_COUNTRY, GRADE;
END LOOP read_loop;

CLOSE cursor_cus;
END$$

DELIMITER ;


